### ISSUE TITLE
Change Sidebar - Icons and Links

### ISSUE THREAD

**Issue by BestMat-Backend** [bestmat-inc/bestdeveloper-bestmat#4]
@BestMat, change all Icons and make sure that they refer to the proper product.
(We can take atleast a few months for this because we have to start developing the products xD)

**Comment by BestMat** [comment]
@BestMat-Backend change in Project or I will ask BestArivu to do it.

**Comment by BestMat** [comment]
@BestMat-Backend bro how is this related to PRODUCT ISSUE
I am closing and deleting this.

**Comment by BestMat** [comment]
Closing this Issue.
